server:
  port: 8081
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test;AUTO_SERVER=TRUE
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  freemarker:
    suffix: .ftl
    content-type: text/html
    charset: UTF-8
    cache: false
  mvc:
    static-path-pattern: /static/**
